# Exercise 5.A NumPy fundamentals

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ["apple", "banana", "cherry", "date"]

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [4]:
print(arr_1.dtype) # output: <U6
# U (Unicode string), 6 (The maximum length of the string in characters)

<U6


In [5]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [7]:
print(arr_2)
# arr_2.T does not alter the value stored in arr_2

[[10 11 12]
 [13 14 15]]


In [8]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [10]:
arr_5 = np.array([[[1, 1], [1, 1], [1, 1]]])
print(arr_5)

[[[1 1]
  [1 1]
  [1 1]]]
