# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [3]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop iterates through the array row by row, multiplying each row's values by 2. The second loop is nested, allowing us to access and multiply each individual element by 2.

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
print(loop_result)

# The nested loop iterates through the second row during the final iteration, leaving
# loop_result holding that row's updated values.

[28 30 32]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [9]:
# stacked_array_2 = np.stack((joined_array_1, joined_array_2))
# print(stacked_array_2)

# ValueError: All input arrays must have the identical shape to be stacked along a new axis.

In [10]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [11]:
# another_2 = np.concatenate((joined_array_1, arrA), axis=1)

# ValueError: The arrays cannot be concatenated along axis 1 because their row counts 
# do not match (joined_array_1 has 4 rows, while arrA has 2 rows).

In [12]:
arrA_h = np.hstack((arrA, arrA))
# stack horizontally along column axis
arrA_v = np.vstack((arrA, arrA))
# stack vertically along row axis
arrA_d = np.dstack((arrA, arrA))
# stack along height/depth

print(f"Using hstack():\n{arrA_h}\n")
print(f"Using vstack():\n{arrA_v}\n")
print(f"Using dstack():\n{arrA_d}")

Using hstack():
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Using vstack():
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Using dstack():
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [13]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# Returns a list containing two 2-dimensional arrays.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [14]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Returns a list of three 2D arrays; the first array contains two rows, 
# while the second and third arrays contain one row each.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [15]:
result_1 = np.where((arrA % 2 == 0), arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [16]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [17]:
print("arrB:\n", arrB)
z = arrB < 7
arrC = arrB[z]
print("\nFilter arrB to get values less than 7")
print("arrC: ", arrC)

arrB:
 [[ 7  6]
 [13  5]
 [ 7  3]]

Filter arrB to get values less than 7
arrC:  [6 5 3]


In [18]:
y = arrB >= 7
arrD = arrB[y]
print("Filter arrB to get values greater than or equal to 7")
print("arrD: ", arrD)

Filter arrB to get values greater than or equal to 7
arrD:  [ 7 13  7]
