# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[14 15]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[14 16]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.20636391]
 [0.60134513]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[76 84 20 94 72]
 [93 95 30 79 60]
 [34 82 97 46 86]
 [73 46 93 37 66]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.60719384 0.80238421 0.53112984 0.98014703 0.08396422]
 [0.88650018 0.48249762 0.99146281 0.75278632 0.65336271]
 [0.49418653 0.72140059 0.46312174 0.37590247 0.44452171]
 [0.9207726  0.74518498 0.12796653 0.27184109 0.26260508]]


## Generating Random Choices from an Array

In [7]:
students = np.array(["Aspenne", "Chantal", "Cris", "Demy", "Dimitri", "Hamzah", 
                     "Ivana", "Jonathan", "Jordan", "Lily", "Malaika", "Marenza"])

In [8]:
call_on = np.random.choice(students)
print(call_on)

Dimitri


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This is not an effective way to assign breakout groups because np.random.choice 
# samples with replacement by default. This causes duplicate student assignments 
# across different groups and redundant names within the same group.

[['Malaika' 'Chantal' 'Jonathan' 'Dimitri']
 ['Malaika' 'Dimitri' 'Jordan' 'Demy']
 ['Lily' 'Demy' 'Malaika' 'Jordan']]


In [10]:
call_on_weighted = np.random.choice(
    students, 
    p=[0.3, 0.0, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05],
    size=5
)
print(call_on_weighted)

# ["Aspenne", "Chantal", "Cris", "Demy", "Dimitri", "Hamzah", "Ivana", "Jonathan", "Jordan", "Lily", "Malaika", "Marenza"]
# [ 0.3,       0.0,       0.1,    0.1,    0.1,       0.1,      0.05,    0.05,       0.05,     0.05,   0.05,      0.05]
# I assigned a 0.3 probability to the first student and 0.0 to the second to satisfy 
# the prompt requirements. The remaining 0.7 probability was distributed among 
# the other students to ensure the total probability sums exactly to 1.0

['Aspenne' 'Malaika' 'Jordan' 'Aspenne' 'Dimitri']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 9.58312996  9.60208426 15.81829073  8.09844127 10.41561627]
 [ 5.68174807 12.57359802 11.68452159 17.2107437  14.78972159]
 [12.68984973 14.03920591  4.13859265  2.68869743  4.76050016]
 [16.98316116 20.73812621 21.70198316  8.09148046 13.73362519]]
