# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

In [3]:
print(r_4)

[[75 70 80 83 38]
 [82 54 36 37 56]
 [39 77 81 83 99]
 [67 45 39 61 65]]


In [4]:
np.random.shuffle(r_4)
print(r_4)

[[82 54 36 37 56]
 [75 70 80 83 38]
 [67 45 39 61 65]
 [39 77 81 83 99]]


I found that shuffle changed the order of the rows, while keeping the elements within each row in their original sequence.

In [5]:
new_shuffle = np.random.permutation(r_4)
print("Using permutation():\n", new_shuffle)
print("\nThe Original array:\n", r_4)

Using permutation():
 [[67 45 39 61 65]
 [39 77 81 83 99]
 [75 70 80 83 38]
 [82 54 36 37 56]]

The Original array:
 [[82 54 36 37 56]
 [75 70 80 83 38]
 [67 45 39 61 65]
 [39 77 81 83 99]]


I will use shuffle() when I want to modify the original array in place, and permutation() when I need a shuffled copy while leaving the original array unchanged.

## Mathematical Operations

In [6]:
print("r_1:\n", r_1)
print("r_1 shape: ", r_1.shape)
print("\nr_2:\n", r_2)
print("r_2 shape: ", r_2.shape)
print("\nThe result of adding r_1 and r_2:\n", np.add(r_1, r_2))
print("result's shape: ", (np.add(r_1, r_2)).shape)

r_1:
 [17 13]
r_1 shape:  (2,)

r_2:
 [[18 10]]
r_2 shape:  (1, 2)

The result of adding r_1 and r_2:
 [[35 23]]
result's shape:  (1, 2)


In [7]:
print("r_1:\n", r_1)
print("r_1 shape: ", r_1.shape)
print("\nr_3:\n", r_3)
print("r_3 shape: ", r_3.shape)
print("\nThe result of adding r_1 and r_3:\n", np.add(r_1, r_3))
print("result's shape: ", (np.add(r_1, r_3)).shape)

r_1:
 [17 13]
r_1 shape:  (2,)

r_3:
 [[0.63807692]
 [0.9496528 ]]
r_3 shape:  (2, 1)

The result of adding r_1 and r_3:
 [[17.63807692 13.63807692]
 [17.9496528  13.9496528 ]]
result's shape:  (2, 2)


In [8]:
print("r_2:\n", r_2)
print("r_2 shape: ", r_2.shape)
print("\nr_4:\n", r_4)
print("r_4 shape: ", r_4.shape)
# print("\nThe result of adding r_2 and r_4:\n", np.add(r_2, r_4))
# print("result's shape: ", (np.add(r_2, r_4)).shape)

# ValueError: operands could not be broadcast together with shapes (1,2) (4,5)

r_2:
 [[18 10]]
r_2 shape:  (1, 2)

r_4:
 [[82 54 36 37 56]
 [75 70 80 83 38]
 [67 45 39 61 65]
 [39 77 81 83 99]]
r_4 shape:  (4, 5)


In [9]:
# print(np.add(r_1, r_4))
# ValueError: operands could not be broadcast together with shapes (2,) (4,5)

# print(np.add(r_3, r_4))
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

# My findings: 
# Attempting to add r_1 (shape (2,)), r_2 (shape (1,2)), or r_3 (shape (2,1)) to r_4 (shape (4,5)) 
# all result in a "ValueError: operands could not be broadcast together".
# This occurs because their trailing dimensions do not match (2 does not match 5, and 2 does not match 4)

In [10]:
print(np.add(np.array([1]), r_4))

[[ 83  55  37  38  57]
 [ 76  71  81  84  39]
 [ 68  46  40  62  66]
 [ 40  78  82  84 100]]


In [11]:
print(np.add(np.array([[1]]), r_4))

[[ 83  55  37  38  57]
 [ 76  71  81  84  39]
 [ 68  46  40  62  66]
 [ 40  78  82  84 100]]


In [12]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[ 83  55  37  38  57]
 [ 76  71  81  84  39]
 [ 68  46  40  62  66]
 [ 40  78  82  84 100]]


In [13]:
# print(np.add(np.array([[1],[1]]), r_4))
# ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

I think broadcasting works by expanding the dimensions of the smaller array to match those of the larger array. The resulting shape is determined by the dimensions of the larger array.

## Rounding

In [14]:
print("r_3:\n", r_3)

r_3:
 [[0.63807692]
 [0.9496528 ]]


In [15]:
print("Round r_3 using trunc():\n", np.trunc(r_3))

Round r_3 using trunc():
 [[0.]
 [0.]]


In [16]:
print("Round r_3 using fix():\n", np.fix(r_3))

Round r_3 using fix():
 [[0.]
 [0.]]


In [17]:
print("Round r_3 using floor():\n", np.floor(r_3))

Round r_3 using floor():
 [[0.]
 [0.]]


In [18]:
print("Round r_3 using ceil():\n", np.ceil(r_3))

Round r_3 using ceil():
 [[1.]
 [1.]]


In [19]:
print("Round r_3 using round():\n", np.round(r_3, 2))

Round r_3 using round():
 [[0.64]
 [0.95]]


## Cumulative Operations

In [20]:
print("r_4:\n", r_4)

r_4:
 [[82 54 36 37 56]
 [75 70 80 83 38]
 [67 45 39 61 65]
 [39 77 81 83 99]]


In [21]:
print("The sum of all values in r_4:\n", np.sum(r_4))

The sum of all values in r_4:
 1267


In [22]:
print("The sum of elements along the 0 axis for r_4:\n", np.sum(r_4, axis=0))

The sum of elements along the 0 axis for r_4:
 [263 246 236 264 258]


In [23]:
print("The sum of elements along the 1 axis for r_4:\n", np.sum(r_4, axis=1))

The sum of elements along the 1 axis for r_4:
 [265 346 277 379]


In [24]:
print("The cumulative sum of values in r_4:\n", np.cumsum(r_4))

The cumulative sum of values in r_4:
 [  82  136  172  209  265  340  410  490  573  611  678  723  762  823
  888  927 1004 1085 1168 1267]


In [25]:
print("The cumulative sum of values along the 0 axis for r_4:\n", np.cumsum(r_4, axis=0))

The cumulative sum of values along the 0 axis for r_4:
 [[ 82  54  36  37  56]
 [157 124 116 120  94]
 [224 169 155 181 159]
 [263 246 236 264 258]]


## Grocery Problem

In [26]:
# [Vegetables, Fruits, Snacks, Beverages]
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print("bag1:\n", bag1)
print("bag2:\n", bag2)

bag1:
 [2 3 4 0]
bag2:
 [4 0 1 2]


In [27]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)
print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items")

The first bag contains 9 items, and the second bag contains 7 items


In [28]:
total = np.sum([bag1, bag2], axis=0)
print(f"There are {total[0]} vegetables, {total[1]} fruits, {total[2]} boxes of snacks, and {total[3]} beverages in the two grocery bags")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

In [29]:
# [Mon, Tue, Wed, Thu, Fri]
ali = np.array([5, 4, 6, 4, 2])

In [30]:
# [Mon, Tue, Wed, Thu, Fri]
ben = np.array([0, 5, 5, 3, 4])

In [31]:
# [Mon, Tue, Wed, Thu, Fri]
carla = np.array([3, 6, 0, 3, 4])

In [32]:
all_knocks = np.array([ali, ben, carla])
print("All door-knocks for the week:\n", all_knocks)

All door-knocks for the week:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [33]:
person_totals = np.sum(all_knocks, axis=1) # [21 17 16]
collective_total = np.sum(all_knocks)
print(f"Total doors knocked by person - Ali: {person_totals[0]}, Ben: {person_totals[1]}, Carla: {person_totals[2]}")
print(f"Total doors knocked by the group collectively: {collective_total}")

Total doors knocked by person - Ali: 21, Ben: 17, Carla: 16
Total doors knocked by the group collectively: 54


In [34]:
daily_group_knocks = np.sum(all_knocks, axis=0) # [ 8 15 11 10 10]
rolling_knocks = np.cumsum(daily_group_knocks) # [ 8 23 34 44 54]

# Convert knocks to estimated votes (1 vote per 2 knocks)
estimated_votes = rolling_knocks / 2

print("Rolling total of estimated votes (Mon through Fri):", estimated_votes)

Rolling total of estimated votes (Mon through Fri): [ 4.  11.5 17.  22.  27. ]
